"""Initial migrations

Revision ID: fd5f96219002
Revises: 
Create Date: 2026-05-29 22:45:49.121772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5f96219002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('licenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('duration_type', sa.String(length=50), nullable=False),
    sa.Column('duration_value', sa.Integer(), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_lifetime', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_category_id'), 'licenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_licenses_key'), 'licenses', ['key'], unique=True)
    op.create_table('license_activations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('license_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('os_info', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=255), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id', 'device_id', name='uq_license_device')
    )
    op.create_index(op.f('ix_license_activations_device_id'), 'license_activations', ['device_id'], unique=False)
    op.create_index(op.f('ix_license_activations_license_id'), 'license_activations', ['license_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_license_activations_license_id'), table_name='license_activations')
    op.drop_index(op.f('ix_license_activations_device_id'), table_name='license_activations')
    op.drop_table('license_activations')
    op.drop_index(op.f('ix_licenses_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_category_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
